# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 安装 node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: 配置Git免密 # StrictHostKeyChecking 首次验证不用输yes
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CI_SECRET_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host *" > ~/.ssh/config
        echo "     StrictHostKeyChecking no" >> ~/.ssh/config
        chmod 644 ~/.ssh/config
        git config --global user.name TMaize
        git config --global user.email 1772314831@qq.com
    - name: 打包&部署
      run: |
        git clone git@github.com:TMaize/vue-admin-template.git vue-admin-template
        cd vue-admin-template
        npm install
        npm run build --if-present
        echo '///////////////////'
        mv dist ..
        git checkout --orphan gh-pages
        rm -rf ./*
        rm -rf .github .browserslistrc .editorconfig .eslintrc.js .gitignore
        cp -r  ../dist/* .
        git add .
        git commit -m "update pages"
        git push --force --progress "origin" gh-pages
    # - name: 部署gh-pages分支
    #   uses: JamesIves/github-pages-deploy-action@3.7.1
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     BRANCH: gh-pages
    #     FOLDER: build
    #     CLEAN: true
    - name: 发送通知
      run: curl "${{ secrets.CI_WEBHOOOK_URL }}" -X POST
